Fail set_cron on invalid expression

diff --git a/overlay/usr/local/bin/pmsset b/overlay/usr/local/bin/pmsset
--- a/overlay/usr/local/bin/pmsset
+++ b/overlay/usr/local/bin/pmsset
@@ -19,9 +19,11 @@ set_cron() {
     if crontab new_cron
     then
       sysrc -f /etc/rc.conf plex_cron="$cron_expression"
+      rm new_cron
+    else
+      echo "Invalid cron expression"
+      exit 1
     fi
-
-    rm new_cron
 }
 
 if [ "$1" = "auto_update" ]
